### ISSUE TITLE
Synchronization problem with browsable dictionary at wwwpdb.org

### ISSUE THREAD

**Issue by pkeller** [pdbxmmcifwg/diffrn-data-set-extension#11]
The browsable development dictionary at http://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v5_next.dic/Index/ is based on an out-of-date version of the base mmCIF dictionary. The issue that I spotted is that the Data Type List at http://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v5_next.dic/Data/index.html contains `non_negative_int`, which is no longer present and according to a comment in the header [here](https://github.com/wwpdb-dictionaries/mmcif_pdbx/blob/ac625197846229f77b96fa2f3ad78647f9681613/base/mmcif_pdbx_v50-header.dic#L2005) was removed almost two years ago.

I find the browsable dictionaries an essential resource, so it would be good to get the development one closer to the current master.

Arguably it would be good to fix and reinstate this type (and also for non negative floats), but that is a subject for another issue.

**Comment by epeisach** [comment]
This looks like some sort of caching - or possibly the conversion from dictionary -> html not removing old files that are no longer relevant.  I will take a look. If I remember non_negative_int was used in one place in an EM extension and seemed redundant as it is an integer with range limits.

**Comment by epeisach** [comment]
Actually - the comment was "Remove use of non_negative_int as regular expression incorrect" -- but it was removed from the V50 dictionary but not v5_next.  That will be corrected in next update.

**Comment by epeisach** [comment]
Latest dictionary has this resolved.
